#2025-05-26 13:56:14
# ==========================================================================
# Properties File:  /home/ws/an7363/proof-run-configurator.properties
# Application:      unknown
# ==========================================================================
# This file contains important settings for the configuration of an application 
# - any property is represented by a leading property name followed by an
#   equal sign ("=") and the values of the entries
# - button text is represented by a string without embracing quote signs
# - color is represented by RGB-values, separated by commas (no Blanks!!)
# - text color is represented by RGB-values, separated by commas (no Blanks!!)
# - comment lines start with '#'.
# - blank lines are allowed
# ==========================================================================
deltaXLocation=100
deltaYLocation=100
proof.worker.block.program.evaluate=false
proof.worker.block.program.testDataPath=/tmp
proof.worker.block.program.workingdir=/develop/WS-PROOF/workspace
proof.worker.directory=/develop/WS-PROOF/proof-worker
proof.worker.logging.logDirectory=/tmp
proof.worker.logging.logLevel=DEBUG
proof.worker.logging.logstash.host=proof2-logstash.cloud.iai.kit.edu
proof.worker.run.modelfiles.override=true
proof.worker.workflow.executionId=WF_uuid__IO-Test-IO
proof.worker.workflow.uuid=IO-Test-IO
server.error.include-binding-errors=always
server.error.include-message=always
server.port=8080
spring.application.name=PROOF 2.0 WORKER
spring.elasticsearch.uris=https://proof2-elastic.cloud.iai.kit.edu:443
spring.main.lazy-initialization=false
spring.main.log-startup-info=false
spring.main.web-application-type=none
spring.output.ansi.enabled=ALWAYS
spring.rabbitmq.host=localhost
spring.rabbitmq.password=admin
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
#spring.rabbitmq.virtual-host=richard
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB
startXLocation=100
startYLocation=100
useTabs=false
proof.worker.useSockets=true
proof.worker.logback.config=/develop/WS-PROOF/proof-worker/logback.xml
proof.processing=local
