#spring.application.name=PROOF 2.0 WORKER
#spring.application.version=@project.version@
#spring.application.buildAt=@maven.build.timestamp@
#spring.main.lazy-initialization=false
#spring.main.log-startup-info=false
#spring.output.ansi.enabled=ALWAYS
#spring.main.web-application-type=none
# RabbitMQ
#spring.rabbitmq.host=141.52.147.157
#spring.rabbitmq.host=localhost
#spring.rabbitmq.host=rabbitmq
#spring.rabbitmq.port=5672
#spring.rabbitmq.password=admin
#spring.rabbitmq.username=admin
#spring.rabbitmq.virtual-host=prod
#Elastic
#spring.elasticsearch.uris=https://proof2-elastic.cloud.iai.kit.edu:443
# program settings
#proof.worker.logging.logLevel=DEBUG
#proof.worker.process.timeout=10
#proof.workspaceDir=/tmp