ARG WORKER_IMAGE
FROM ${WORKER_IMAGE}
# Install Python
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        python3 \
        python3-venv \
    && rm -rf /var/lib/apt/lists/*

ENV PATH="/opt/venv/bin:$PATH"

# Install Python library
COPY proof-sim-core/dist/*.whl /tmp/

RUN python3 -m venv /opt/venv

RUN pip install --no-cache-dir /tmp/*.whl \
    && rm -f /tmp/*.whl