FROM python:3.12-slim AS python-build-test
COPY proof-sim-core/dist/ /wheels
RUN pip install --no-cache-dir /wheels/proof_sim_core-*.whl


FROM proof-worker:local AS final
ENV PYTHONUNBUFFERED=1
COPY --from=python-build-test /usr/local/bin/python* /usr/local/bin/
COPY --from=python-build-test /usr/local/lib /usr/local/lib